---
driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    cpus: 1
    memory: 1024

provisioner:
  name: chef_zero
  chef_client_path: /usr/bin/chef-client
  require_chef_omnibus: 12.14.89

transport:
  name: sftp

platforms:
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[simple-hazelcast-test]
    attributes:
      hazelcast:
        class_path:
          custom_path: /tmp
        java_opts:
          mem: -Xmx512m
          test_opt: -DtestOpt=true
          config: -Dconfig.xml=/tmp/config.xml

