---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: chef/debian-7.7
    platform: debian
    driver_config:
      provision_command:
        - apt-get -y install build-essential

  - name: chef/centos-7.0


suites:
  - name: default
    run_list:
      - recipe[simple-hazelcast-test]
    attributes:
      hazelcast:
        java_opts:
          - -Xmx512m
          - -DtestOpt=true
          - -Dconfig.xml=/tmp/config.xml

